### ISSUE TITLE
Feature Request - Support Text Formatting for Pull Descriptions

### ISSUE THREAD

**Issue by mikeyv19** [RaiderIO/keystone.guru#2176]
Would love the ability to format text within "Pull Descriptions". Don't need a fancy formatting bar, but if something like HTML tags were supported within the text box, that would be a nice feature.

Having the ability to do line breaks or bold certain things personally helps make the route more readable for me.

**Comment by Wotuu** [comment]
I like the idea, but I'll have to play around with what feels good. Thanks for the suggestion 👍

**Comment by Wotuu** [comment]
Heya, sorry this took so long! I just got around to doing this. How does this look? It supports these tags atm, if you want to see more added let me know!

**Comment by Wotuu** [comment]
![image](https://github.com/RaiderIO/keystone.guru/assets/811809/67169968-d8da-477c-9f6a-2db7d94539da)

**Comment by mikeyv19** [comment]
Thank you! Looks great, appreciate the follow up - still using Keystone guru every season XD - is this rolled into live yet or future release?

**Comment by Wotuu** [comment]
Good to hear! Feedback like yours make the site better for everyone - so keep it coming please 😄. This is not live yet, but I will push it live soon. Maybe tomorrow, otherwise Sunday!

**Comment by Wotuu** [comment]
@mikeyv19 This is now deployed to production, enjoy and let me know how you like it!
