### ISSUE TITLE
npc class data for shadowlands dungeons is incomplete

### ISSUE THREAD

**Issue by ghost** [RaiderIO/keystone.guru#908]
Not all maps have proper markings for ranged/caster/healer/melee NPCs.

Work in progress checklist:
- [x] De Other Side
- [x] Halls of Atonement
- [x] Mists of Tirna Scithe
- [x] Plaguefall
- [ ] Sanguine Depths
- [ ] Spires of Ascension
- [ ] The Necrotic wake
- [ ] Theater of pain

**Comment by omicron-o** [comment]
DoS has some classifications that aren't entirely clear I think. I've marked the risen cultists, the death speakers and the sentient slimes as casters. It's not clear to me they should be casters, but they sure feel like them. Feel free to revert my changes on those if you disagree.

The cultists and the death speaker will melee a lot and they even run into melee without needing kicks, so it's not entirely clear they should be casters. `UnitClass` has them listed as paladins, which seems to be used for (almost?) all caster mobs in the game, but also for some that aren't really casters (such as the risen bonesoldiers in DoS).

The game has the sentient slimes listed as warrior mobs, but they just spam their casts.

**Comment by Wotuu** [comment]
Closing this for now - this data is not really relevant anymore, a lot of other dungeons have this information missing so it'd be a bigger effort to get this all corrected.
